apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-flask
  labels:
    app: flask
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask-app
          image: {{ .Values.flask.image }}
          ports:
            - containerPort: {{ .Values.flask.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}